spring:
  application:
    name: bus-ticketing-api-gateway

  # KEYCLOAK CONFIGURATION
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/auth/realms/bus-ticketing/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/auth/realms/bus-ticketing/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: http://localhost:8080/auth/realms/bus-ticketing/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/auth/realms/bus-ticketing/protocol/openid-connect/certs
            user-info-authentication-method: header
        registration:
          bus-ticketing-client:
            provider: keycloak
            client-id: bus-ticketing-client
            client-secret: IP124tvUDtKZvnbiuIJx28MUjM2ylO8q
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/bus-ticketing/protocol/openid-connect/certs

  zipkin:
    base-url: http://localhost:9411

  # GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        # USER MANAGEMENT SERVICE
        - id: bus-ticketing-user-service
          uri: lb://bus-ticketing-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        # FLEET MANAGEMENT SERVICE
        - id: bus-ticketing-fleet-service
          uri: lb://bus-ticketing-fleet-service
          predicates:
            - Path=/fleet/**
          filters:
            - StripPrefix=1

        # ROUTE MANAGEMENT SERVICE
        - id: bus-ticketing-route-service
          uri: lb://bus-ticketing-route-service
          predicates:
            - Path=/route/**
          filters:
            - StripPrefix=1

        # BOOKING SERVICE
        - id: bus-ticketing-booking-service
          uri: lb://bus-ticketing-booking-service
          predicates:
            - Path=/booking/**
          filters:
            - StripPrefix=1

        # TICKET SERVICE
        - id: bus-ticketing-ticket-service
          uri: lb://bus-ticketing-ticket-service
          predicates:
            - Path=/ticket/**
          filters:
            - StripPrefix=1

        # PAYMENT SERVICE
        - id: bus-ticketing-payment-service
          uri: lb://bus-ticketing-payment-service
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1

        # LIVE TRIP UPDATES SERVICE
        - id: bus-ticketing-trip-updates-service
          uri: lb://bus-ticketing-trip-updates-service
          predicates:
            - Path=/trip-updates/**
          filters:
            - StripPrefix=1

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
